    # title of website
title: East导航

# description of website
description: e888888's navigation site

# favicon of website
favicon: "https://github.com/e888888.png?size=40"

# your website url
url: https://e888888.github.io/E888888.github.io/

# footer message
footer: © 2020-2025__诚谢：<a href="https://github.com/x1ah" target="_blank">x1ah</a> 模版开源

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - baidu
      - zhihu
      - github
      - weibo
      - bilibili

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 秘塔Ai搜索
          description: 没有广告，直达结果。
          url: https://metaso.cn
        - name: AmyMind
          description: Ai思维导图生成器，轻松创建思维导图。
          url: https://amymind.com/zh-cn
        - name: Github
          description: 一个在线的、基于Git的版本控制和代码托管平台。
          url: https://github.com          
        - name: 微步云沙箱
          description: 在线文件威胁分析，高效检测20种大类威胁、1000+木马家族、1000+APT组织。
          url: https://s.threatbook.com
        - name: 白描
          description: 高效准确的图片转文字识别、提取。
          url: https://web.baimiaoapp.com
        - name: Wormhole
          description: 文件临时分享；端到端加密和自动过期链接，确保分享的文件私密。
          url: https://wormhole.app
        - name: IP111
          description: 全方位查询您的IP地址。
          url: https://www.ip111.cn
        - name: 天启接码
          description: 专业号码接收服务。
          url: https://www.tqsms.xyz
